# This is a staging compose file for testing the production build locally. It is not used in the deployment process.
services:
  web:
    build:
      context: .
      target: production  # Use "production" for production builds
    container_name: launchpad-web
    ports:
      - "9000:9000"
    env_file:
      - .env  # Load environment variables from a .env file
    environment:
      - DJANGO_ENV=production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
  nginx:
    image: nginx:1.27.3-perl
    container_name: launchpad-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web
  # tunnel:
  #   image: cloudflare/cloudflared:2024.12.2
  #   container_name: launchpad-tunnel
  #   command: tunnel --no-autoupdate --config /app/config.yml run
  #   volumes:
  #     - ./tunnel/config.yml:/app/config.yml
  #   environment:
  #     - TUNNEL_ID=${TUNNEL_ID}
  #     - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  #     - TZ=America/Los_Angeles
  #   depends_on:
  #     - web
  #   restart: unless-stopped
  #   hostname: launchpad.nicholasfournier.com

volumes:
  static_volume:
  media_volume: