services:
  web:
    image: nichfournier/launchpad-web:latest
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - DJANGO_ENV=production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
  nginx:
    image: nichfournier/launchpad-nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web
  tunnel:
    image: nichfournier/launchpad-tunnel:latest
    command: tunnel --no-autoupdate --config /app/config.yml run
    volumes:
      - ./tunnel.yml:/app/config.yml
    environment:
      - TUNNEL_ID=${TUNNEL_ID}
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TZ=America/Los_Angeles
    depends_on:
      - web
    restart: unless-stopped
    hostname: launchpad.nicholasfournier.com

volumes:
  static_volume:
  media_volume: