name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Checkout the code
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Initialize and update submodules

    - name: Build the Docker image
      run: |
        ls
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/launchpad-web:latest
        docker build ./nginx --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/launchpad-nginx:latest
        docker build ./tunnel --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/launchpad-tunnel:latest

    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/launchpad-web:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/launchpad-nginx:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/launchpad-tunnel:latest